const actionTypes = {
	FETCH_BLOGS_REQUEST: 'FETCH_BLOGS_REQUEST',
	FETCH_BLOGS_SUCCESS: 'FETCH_BLOGS_SUCCESS',
	FETCH_BLOGS_ERROR: 'FETCH_BLOGS_ERROR',

	NEXT_BLOG_REQUEST: 'NEXT_BLOG_REQUEST',
	NEXT_BLOG_SUCCESS: 'NEXT_BLOG_SUCCESS',
	NEXT_BLOG_ERROR: 'NEXT_BLOG_ERROR',

	PREVIOUS_BLOG_REQUEST: 'PREVIOUS_BLOG_REQUEST',
	PREVIOUS_BLOG_SUCCESS: 'PREVIOUS_BLOG_SUCCESS',
	PREVIOUS_BLOG_ERROR: 'PREVIOUS_BLOG_ERROR'
};

export default actionTypes;
