const actionTypes = {
	FETCH_BLOGS_REQUEST: 'FETCH_BLOGS_REQUEST',
	FETCH_BLOGS_SUCCESS: 'FETCH_BLOGS_SUCCESS',
	FETCH_BLOGS_ERROR: 'FETCH_BLOGS_ERROR',

	SLIDER_BLOG_REQUEST: 'SLIDER_BLOG_REQUEST',
	SLIDER_BLOG_SUCCESS: 'SLIDER_BLOG_SUCCESS',
	SLIDER_BLOG_ERROR: 'SLIDER_BLOG_ERROR',

	SINGLE_BLOG_REQUEST: 'SINGLE_BLOG_REQUEST',
	SINGLE_BLOG_SUCCESS: 'SINGLE_BLOG_SUCCESS',
	SINGLE_BLOG_ERROR: 'SINGLE_BLOG_ERROR'
};

export default actionTypes;
